---
- name: Destroy loop and his partition
  hosts: loopdevice
  vars:
    ansible_path: "{{ playbook_dir }}/../.."
    mapper_prefix: "linstor_"
  become: true
  gather_facts: true

  vars_prompt:
    name: "confirm_destroy"
    prompt: "This will destroy the loopback device disks used for piraeus/linbit. Make sure piareus is also uninstalled first. Sure to continue? [y/N]"
    default: "n"
    private: no
  any_errors_fatal: yes

  pre_tasks:
    - name: check confirm
      fail:
        msg: "Abort!!"
      when: confirm_destroy != "y"

  tasks:
    - name: Print loop devices
      ansible.builtin.debug:
        msg: "loop_device to be deleted = {{ loop_disk_device }}"

    - name: Umount loop device
      shell: >
        losetup -D /dev/loop0

    - name: Zap the drives
      become: true
      shell: >
        sgdisk --zap-all {{ loop_disk_device }} || true

    - name: Remove lvm partitions
      become: true
      shell: "{{ item }}"
      loop:
      - ls /dev/mapper/{{ mapper_prefix }}* | xargs -I% -- fuser --kill %
      - ls /dev/mapper/{{ mapper_prefix }}* | xargs -I% -- dmsetup clear %
      - ls /dev/mapper/{{ mapper_prefix }}* | xargs -I% -- dmsetup remove -f %
      - ls /dev/mapper/{{ mapper_prefix }}* | xargs -I% -- rm -rf %
      ignore_errors: true

    - name: SSD block delete without restart
      become: true
      shell: >
        blkdiscard {{ loop_disk_device }} && sync

    - name: Wipe the block device
      become: true
      command: "wipefs -af {{ loop_disk_device }}"

    - name: Recursively remove directory
      ansible.builtin.file:
        path: "/etc/lvm/{{ item }}"
        state: absent
      loop:
        - archive
        - backup
      tags: ["debug"]

    - name: Re-mount loop device
      shell: >
        losetup /dev/loop0 {{ loop_disk_device }}
      tags: [ "mount" ]
