external-secrets:
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

  webhook:
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi

  certController:
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 128Mi

