apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teamspeak-s3.fullname" . }}
  labels:
    {{- include "teamspeak-s3.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.env | nindent 2 }}
