{{- if .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "teamspeak-s3.fullname" . }}-vault-sync
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.target.name }}
  data:
{{- range .Values.externalSecrets.properties }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.externalSecrets.key }}
      property: {{ . }}
{{- end }}
{{- end }}
