{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamspeak-s3.fullname" . }}-secret
data:
{{- range $key, $val := .Values.secrets.properties }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end }}
