---

- name: "Download and extract binary"
  ansible.builtin.get_url:
    url: "{{ nerdctl_url }}"
    checksum: "sha256:https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version }}/SHA256SUMS"
    dest: "/opt/nerdctl.tar.gz"
    owner: root
    group: root
    mode: 0755

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "/opt/nerdctl.tar.gz"
    dest: "/usr/local/bin"
    creates: "/usr/local/bin/nerdctl"
    remote_src: true

- name: Ensures /etcd subdir exists
  file:
    path: "/etc/nerdctl"
    state: directory
    owner: root
    group: root
    mode: 0655

# https://github.com/containerd/nerdctl/blob/master/docs/config.md
- name: Create config.
  ansible.builtin.template:
    src: "nerdctl.toml.j2"
    dest: "/etc/nerdctl/nerdctl.toml"
