kyverno:

  # TODO: change this to "mode: ha" when the new version gets released
  # https://kyverno.io/docs/installation/#security-vs-operability
  # https://kyverno.io/docs/installation/#high-availability
  replicaCount: 1

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: kyverno

