node-feature-discovery:
  worker:
    resources:
      requests:
        cpu: 25m
        memory: 18Mi
      limits:
        cpu: 25m
        memory: 18Mi
    config:
      core:
        #labelWhiteList: null   ## Default to null but gives an error if we define it like null
        noPublish: false
        sleepInterval: 60s
        featureSources:
          - all
          - -cpu
          - -local
          - -kernel
          - -system
        labelSources:
          - all
        klog:
          addDirHeader: false
          alsologtostderr: false
          logBacktraceAt: ""
          logtostderr: true
          skipHeaders: false
          stderrthreshold: 2
          v: 0
          vmodule: ""
      #   NOTE: the following options are not dynamically run-time configurable
      #         and require a nfd-worker restart to take effect after being changed
          logDir: ""
          logFile: ""
          logFileMaxSize: 1800
          skipLogHeaders: false
      sources:
        cpu:
          cpuid:
            # NOTE: whitelist has priority over blacklist
            attributeBlacklist:
              - "BMI1"
              - "BMI2"
              - "CLMUL"
              - "CMOV"
              - "CX16"
              - "ERMS"
              - "F16C"
              - "HTT"
              - "LZCNT"
              - "MMX"
              - "MMXEXT"
              - "NX"
              - "POPCNT"
              - "RDRAND"
              - "RDSEED"
              - "RDTSCP"
              - "SGX"
              - "SSE"
              - "SSE2"
              - "SSE3"
              - "SSE4"
              - "SSE42"
              - "SSSE3"
            attributeWhitelist:
        pci:
          deviceClassWhitelist:
            - "0200"
            - "03"
            - "12"
          deviceLabelFields:
            - "class"
            - "vendor"
            - "device"
            - "subsystem_vendor"
            - "subsystem_device"
        usb:
          deviceClassWhitelist:
            - "02"
            - "0e"
            - "ef"
            - "fe"
            - "ff"
          deviceLabelFields:
            - "class"
            - "vendor"
            - "device"
        custom:
          # lspci -nn -> [class]:XXX [vendor:device]
          # lspci -d [vendor code]: or lspci -d :[device code].
          - name: "intel-eth"
            labels:
              intel-eth: "true"
            matchFeatures:
              - feature: pci.device
                matchExpressions:
                  vendor: {op: In, value: ["8086"]}
                  #device: {op: In, value: ["15a1"]}
                  class: {op: In, value: ["0200"]}
          - name: "intel-gpu"
            labels:
              intel-gpu: "true"
            matchFeatures:
              - feature: pci.device
                matchExpressions:
                  vendor: {op: In, value: ["8086"]}
                  #device: {op: In, value: ["5a85", "0412"]}
                  class: {op: In, value: ["0300"]}
          - name: "intel-card-reader"
            labels:
              intel-card-reader: "true"
            matchFeatures:
              - feature: pci.device
                matchExpressions:
                  vendor: {op: In, value: ["10ec"]}
                  device: {op: In, value: ["5229"]}
          - name: "zigbee-cc2531"
            labels:
              ti-cc2531: "true"
            matchFeatures:
              - feature: usb.device
                matchExpressions:
                  class: {op: In, value: ["02"]}
                  vendor: {op: In, value: ["0451"]}
                  device: {op: In, value: ["16a8"]}

  master:
    replicaCount: 1
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
    resources:
      requests:
        cpu: 25m
        memory: 22Mi
      limits:
        cpu: 50m
        memory: 128Mi
