apiVersion: cert-manager.io/v1
kind: Certificate  # https://cert-manager.io/docs/concepts/certificate/#certificate-lifecycle
metadata:
  name: acme-crt
spec:
  secretName: acme-crt-secret
  issuerRef:
    name: letsencrypt-prod-dns
#    name: letsencrypt-stag-dns
    kind: ClusterIssuer
  dnsNames:
  - "{{ $.Values.homelabDnsDomain }}"
  - "*.{{ $.Values.homelabDnsDomain }}"
  - "*.{{ $.Values.homelabExternalDomain }}.{{ $.Values.homelabDnsDomain }}"
  - "*.{{ $.Values.homelabInternalDomain }}.{{ $.Values.homelabDnsDomain }}"