reloader:
  nameOverride: reloader

  fullnameOverride: reloader

  reloader:
    podMonitor:
      enabled: false
      namespace: monitoring

  resources:
    requests:
      cpu: 15m
      memory: 64M
    limits:
      memory: 64M
