# external-secrets.io/v1alpha1 ExternalSecret is deprecated; use external-secrets.io/v1beta1 ExternalSecret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    # target Secret name
    name: example-sync
  data:
    # k8s secret key
  - secretKey: foobar
    remoteRef:
      # Vault key path 
      key: path/to/my/secret
      # Vault property
      property: password
