apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      #server: https://vault.vault-server:8200
      server: https://vault.k3s.lorien.cloud
      # vault enterprise namespace: https://www.vaultproject.io/docs/enterprise/namespaces
      path: secret
      version: "v2"
      # base64 encoded string of certificate
      #caBundle: "..."
      # Instead of caBundle you can also specify a caProvider
      # this will retrieve the cert from a Secret or ConfigMap
      #caProvider:
      #  # Can be Secret or ConfigMap
      #  type: "Secret"
      #  name: "my-cert-secret"
      #  key: "cert-key"
      auth:
         kubernetes:
           mountPath: "kubernetes"
           role: "external-secretes"
