---
- name: Check requirements
  assert:
    that:
      - ansible_path is defined
      - cloudflare_email is defined
      - cloudflare_api_key is defined
      - cloudflare_account_id is defined

# Create namespaces because the helm template doesn't create them and we will need
# to create secrets with terraform to store cloudlfare API tokens

- name: Ensure required namespaces exist
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: present
  loop:
    - cert-manager
    - external-dns
    - openebs-localpv
    - nf-discovery
    - vault-operator
    - vault-server
  environment:
    KUBECONFIG: "{{ ansible_path }}/kubeconfig.yaml"
  tags: [ "namespaces" ]

# Create terraform tfvars
- name: Render environment file
  template:
    src: terraform.tfvars.j2
    dest: "{{ ansible_path }}/../external/terraform.tfvars"
    mode: 0640
  tags: [ "terraform" ]
