apiVersion: v2
name: postgres-operator
version: 0.0.1
dependencies:
  - name: postgres-operator
    version: 1.10.0
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
