apiVersion: v1 
kind: Pod
metadata:
  name: demo-pod-xfs-1
  namespace: default
spec:
  containers:
  - name: demo-pod-xfs-1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 1000s; done"]
    volumeMounts:
      - mountPath: "/data"
        name: demo-vol
  volumes:
    - name: demo-vol
      persistentVolumeClaim:
        claimName: pvc-claim-xfs-1
---
apiVersion: v1 
kind: Pod
metadata:
  name: demo-pod-1
  namespace: default
spec:
  containers:
  - name: demo-pod-1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 1000s; done"]
    volumeMounts:
      - mountPath: "/data"
        name: demo-vol
  volumes:
    - name: demo-vol
      persistentVolumeClaim:
        claimName: pvc-claim-1
---
apiVersion: v1 
kind: Pod
metadata:
  name: demo-pod-2
  namespace: default
spec:
  containers:
  - name: demo-pod-2
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 1000s; done"]
    volumeMounts:
      - mountPath: "/data"
        name: demo-vol
  volumes:
    - name: demo-vol
      persistentVolumeClaim:
        claimName: pvc-claim-2
---
apiVersion: v1 
kind: Pod
metadata:
  name: demo-pod-3
  namespace: default
spec:
  containers:
  - name: demo-pod-3
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 1000s; done"]
    volumeMounts:
      - mountPath: "/data"
        name: demo-vol
  volumes:
    - name: demo-vol
      persistentVolumeClaim:
        claimName: pvc-claim-3
