# https://github.com/piraeusdatastore/piraeus-operator/blob/master/examples/resource-requirements.yaml
.minimal-resouces: &minimal-resources
  # Resources for a minimal stateless go container.
  limits:
    memory: "250Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

installCRDs: true

webhook:
  timeoutSeconds: 4

operator:
  #resources: *minimal-resources
  resources: {}

kubeRbacProxy:
  #resources: *minimal-resources
  resources: {}

tolerations:
  - key: node-role.kubernetes.io/control-plane # New value since Kubernetes 1.24
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
