---
# https://docs.cilium.io/en/v1.10/gettingstarted/k3s/
- name: "Download binary {{ cilium_url }}"
  ansible.builtin.get_url:
    url: "{{ cilium_url }}"
    checksum: "sha256:{{ cilium_sha256[cilium_arch] }}"
    dest: "{{ cilium_downloaded_file }}"
    owner: root
    group: root
    mode: 0755

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "{{ cilium_downloaded_file }}"
    dest: "/usr/local/bin"
    creates: "/usr/local/bin/cilium"
    remote_src: true

- name: Validate install
  ansible.builtin.command:
    cmd: cilium status -n cilium --wait
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: validate_cilium

- name: Show validate output
  debug:
    var: validate_cilium.stdout
