---
cilium_version: "0.13.1"
cilium_arch: "amd64"
cilium_url: "https://github.com/cilium/cilium-cli/releases/download/v{{ cilium_version }}/cilium-linux-{{ cilium_arch }}.tar.gz"
cilium_downloaded_file: "/opt/cilium_v{{ cilium_version }}.tar.gz"

cilium_sha256:
  amd64: dfabb7a080cd2ae40c71e51980183949bd5ce76184ac439ef32f988825cb275d
  arm64: 8f17d27803ecbfd05eb6b010d8dda9afc9b86832f3dad5fef25e42e77a1083dc
