cert-manager:
  installCRDs: true

  extraArgs:
  # When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted
  - --enable-certificate-owner-ref=true

  global:
    leaderElection:
      namespace: cert-manager

  resources:
    requests:
      cpu: 10m
      memory: 32Mi

  prometheus:
    enabled: false
    servicemonitor:
      enabled: false

  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi

  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
