apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  namespace: metallb-system
data:
  config: |-
    address-pools:
    - name: my-ip-space
      protocol: layer2
      addresses:
      - 192.168.1.245-192.168.1.250

