vault-operator:
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 64Mi

  monitoring:
    serviceMonitor:
      enabled: false
      additionalLabels: {}
      metricRelabelings: []
      relabelings: []

